version: '2'
services:
  ensino-app:
    image: ensino
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ensino-postgresql:5432/ensino
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ensino-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ensino-elasticsearch:9200
    ports:
      - 8080:8080
  ensino-postgresql:
    extends:
      file: postgresql.yml
      service: ensino-postgresql
  ensino-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ensino-elasticsearch
